# Generated by Django 5.1.6 on 2025-06-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
