# Generated by Django 5.1.6 on 2025-06-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_alter_billing_mobile_alter_billing_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
