# Generated by Django 5.1.6 on 2025-06-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_alter_billing_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='ordernotes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='billing',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
