# Generated by Django 5.1.6 on 2025-06-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_orderrs_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrs',
            name='product_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
