# Generated by Django 5.1.6 on 2025-06-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_orderrs_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrs',
            name='product_name',
        ),
    ]
