# Generated by Django 5.1.6 on 2025-07-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_remove_orderrs_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.AlterField(
            model_name='orderrs',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
