# Generated by Django 5.1.6 on 2025-07-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0012_alter_orderrs_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrs',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
