# Generated by Django 5.1.6 on 2025-07-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0013_alter_orderrs_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrs',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
